//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusStationEntities : DbContext
    {
        public BusStationEntities()
            : base("name=BusStationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus_Routes> Bus_Routes { get; set; }
        public virtual DbSet<Buses> Buses { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Passenger_Tickets> Passenger_Tickets { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Roads> Roads { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Tickets_Price> Tickets_Price { get; set; }
        public virtual DbSet<Workers> Workers { get; set; }
    }
}
