//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tickets()
        {
            this.Passenger_Tickets = new HashSet<Passenger_Tickets>();
        }
    
        public int ID_Ticket { get; set; }
        public int Number_Route { get; set; }
        public int Price_ID { get; set; }
        public int Worker_ID { get; set; }
    
        public virtual Bus_Routes Bus_Routes { private get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passenger_Tickets> Passenger_Tickets { private get; set; }
        public virtual Tickets_Price Tickets_Price { private get; set; }
        public virtual Workers Workers { private get; set; }
    }
}
